### ISSUE TITLE
errors on build

### ISSUE THREAD

**Issue by doubletaketech** [meteorhacks/npm#66]
I'm trying to install this http://jsreport.net/learn/nodejs-client 
but I get these errors after running npm install and then running meteor.  App fails to build.  I'm using Meteor 1.0 

Any ideas?

Thanks,
Don

While Building the application:
node_modules/jsreport-client/node_modules/jaydata/node_modules/qs/lib/head.js:3:3: Unexpected end of input
node_modules/jsreport-client/node_modules/jaydata/node_modules/qs/lib/tail.js:2:1: Unexpected token }
node_modules/jsreport-client/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token ILLEGAL
node_modules/jsreport-client/node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/examples/async-generators/0.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/examples/async-generators/1-return.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/examples/async-generators/2-error-propagation.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/examples/async-generators/3-wishful-thinking.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/examples/async-generators/4-shim.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/qs/test/browser/index.html:1: bad formatting in HTML template
node_modules/jsreport-client/node_modules/jaydata/node_modules/acorn/test/bench.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/acorn/test/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/request/node_modules/node-uuid/test/test.html:1: bad formatting in HTML template
node_modules/jsreport-client/node_modules/jaydata/node_modules/acorn/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
node_modules/jsreport-client/node_modules/jaydata/node_modules/q/q-spec.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

**Comment by JamborJan** [comment]
Hey guys,

I have the same issue. 

First I install ```meteorhacks:npm```.

```
$ meteor add meteorhacks:npm
Changes to your project's package version selections:
meteorhacks:async  added, version 1.0.0
meteorhacks:npm    added, version 1.2.2
meteorhacks:npm: Use npm modules with your Meteor App
```

Then I install my desired npm package, in this case I want to use a soap client (see: https://github.com/vpulim/node-soap).

```
$ npm install soap
soap@0.6.1 node_modules/soap
├── strip-bom@0.3.1 (first-chunk-stream@0.1.0, is-utf8@0.2.0)
├── sax@0.6.1
├── lodash@2.4.1
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, form-data@0.2.0, bl@0.9.3, tough-cookie@0.12.1, hawk@1.1.1)
```
Now I edit the ```packages.json``` file.

```
jj@sandstorm-dev:~/ZenFeedback$ nano packages.json
```

And I enter the package information including the correct version:

```
{
  "soap": "0.6.1"
}
```
Then I start my app with ```meteor```. Important: I didn't use anything of the new npm package in my code so far. but anyway the build fails.

```
$ meteor
[[[[[ ~/APPNAME ]]]]]
=> Started proxy.
npm-container: updating npm dependencies -- soap...
=> Started MongoDB.
=> Errors prevented startup:
   While building the application:
   node_modules/soap/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token ILLEGAL
   node_modules/soap/node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
   node_modules/soap/node_modules/strip-bom/cli.js:1:15: Unexpected token ILLEGAL
   node_modules/soap/node_modules/request/node_modules/node-uuid/test/test.html:1: bad formatting in HTML template
   node_modules/soap/node_modules/sax/examples/test.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   node_modules/soap/node_modules/sax/LICENSE-W3C.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
=> Your application has errors. Waiting for file change.
```
Any help or ideas?

@doubletaketech  maybe you can rename the issue to "Unexpected token ILLEGAL errors on build" to have it a bit more specific?

**Comment by JamborJan** [comment]
Any feedback on that one @arunoda ?

**Comment by arunoda** [comment]
Not sure about this issue. 
We simply use meteor's npm usage. 

Try to use this npm module, inside a package. If that does not cause an issue that's wrong with this module.

**Comment by JamborJan** [comment]
I now checked some stuff because I had the Debian package installed like described here: https://github.com/joyent/node/issues/3911#issuecomment-12798913

Still not working.

I'm not quite sure what you mean by "Try to use this npm module".

I installed several npm packages like you described it here: https://github.com/meteorhacks/npm

And none is working. I'll try to do further tests now ... maybe I find something. If you have any idea I would appreciate feedback.

**Comment by JamborJan** [comment]
Hey @arunoda 

I'm not quite sure where it is comming from but in my case it was:

The first line ```#!/usr/bin/env node``` in the three first errors.

```
node_modules/soap/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token ILLEGAL
node_modules/soap/node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
node_modules/soap/node_modules/strip-bom/cli.js:1:15: Unexpected token ILLEGAL
```

Removing the line fixed the issue.

The two errors about DOCTYPE are easy to solve but are switching and appear as:

```
node_modules/soap/node_modules/request/node_modules/node-uuid/test/test.html:1: bad formatting in HTML template
```
I'm still figuring out what this means but all points to soap and not your package.

**Comment by JamborJan** [comment]
when these errors are fixed I run into others ... but as said seems to be an issue of the NPM package I want to install not the 

In case you have an idea where that comes from a short answer is appreciated but you can also close the issue I think.

```
W20150120-13:44:06.053(1)? (STDERR)           
W20150120-13:44:06.223(1)? (STDERR) /home/jj/.meteor/packages/meteor-tool/.1.0.38.ieqxkv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150120-13:44:06.225(1)? (STDERR) 						throw(ex);
W20150120-13:44:06.227(1)? (STDERR) 						      ^
W20150120-13:44:06.228(1)? (STDERR) ReferenceError: exports is not defined
W20150120-13:44:06.230(1)? (STDERR)     at app/node_modules/soap/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:27:1
W20150120-13:44:06.232(1)? (STDERR)     at app/node_modules/soap/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:109:3
W20150120-13:44:06.233(1)? (STDERR)     at /home/jj/ZenFeedback/.meteor/local/build/programs/server/boot.js:175:10
W20150120-13:44:06.234(1)? (STDERR)     at Array.forEach (native)
W20150120-13:44:06.235(1)? (STDERR)     at Function._.each._.forEach (/home/jj/.meteor/packages/meteor-tool/.1.0.38.ieqxkv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150120-13:44:06.237(1)? (STDERR)     at /home/jj/ZenFeedback/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
```

**Comment by chip** [comment]
I'm running into a similar issue, except I think it's a problem with the `request`package:

```
   While building the application:
   node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15: Unexpected token
   ILLEGAL
   node_modules/request/node_modules/bl/test/sauce.js:1:15: Unexpected token ILLEGAL
   node_modules/request/node_modules/node-uuid/test/test.html:1: bad formatting in HTML template
```

**Comment by vikash20186** [comment]
Did you find the solution? I am running into same issue. I am trying to use archiver npm module inside meteor apps.

   node_modules/archiver/node_modules/tar-stream/node_modules/bl/test/sauce.js:1:15:
   Unexpected token ILLEGAL
   node_modules/archiver/node_modules/async/support/sync-package-managers.js:1:15:
   Unexpected token ILLEGAL

**Comment by JamborJan** [comment]
Hey @vikash20186 and @chip 

Unfortunately no more feedback on this topic. I solved my issue by using different technology. I wanted to do it in meteor but now it is not. Sorry that I have no other answer.

Maybe @arunoda has a hint for you but it seems to be an issue with your setup / environment. Maybe you are lucky with one of these answeres:

https://stackoverflow.com/search?q=Unexpected+token+ILLEGAL

(They usually can help :-) ).

**Comment by vikash20186** [comment]
Thanks for looking into it. I fixed it after doing lot of hit and trials.
Just installed the npm module globally using -g option. It works perfectly
fine now.

On Wednesday, June 17, 2015, JJ <notifications@github.com> wrote:

> Hey @vikash20186 <https://github.com/vikash20186> and @chip
> <https://github.com/chip>
>
> Unfortunately no more feedback on this topic. I solved my issue by using
> different technology. I wanted to do it in meteor but now it is not. Sorry
> that I have no other answer.
>
> Maybe @arunoda <https://github.com/arunoda> has a hint for you but it
> seems to be an issue with your setup / environment. Maybe you are lucky
> with one of these answeres:
>
> https://stackoverflow.com/search?q=Unexpected+token+ILLEGAL
>
> (They usually can help :-) ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteorhacks/npm/issues/66#issuecomment-112653630>.
>


-- 
Cheers
Vikash Agarwal

+1 732 208 6551
Piscataway, New Jersey, USA.

**Comment by demitree** [comment]
I've got exactly the same error when I tried to install elasticsearch npm module in my meteor project. 

the option 'g' does simply change the installation path, but the 'cannot find module' error still exists, how you fix it?

**Comment by zwarag** [comment]
Had the same or at least quite same issue and used this approach to solve it.

http://stackoverflow.com/a/19356742/1117736

**Comment by yozawiratama** [comment]
i got the problem, 
it because i use `npm install`

i delete `node_module` folder,
dont use `npm install`,

just register your npm pakacet to package.json like docs said.

i wish this help you guys

**Comment by mikeatlas** [comment]
@zwarag oddly this solved it for me too. http://stackoverflow.com/a/19356742/1117736

`rm -rf node_modules` and restarted my meteor app.
